### ISSUE TITLE
The api IStatelessServiceInstance.Open on node XXXX is stuck

### ISSUE THREAD

**Issue by kayoshino** [microsoft/service-fabric#1052]
Service Fabric Runtime Version: 7.1.458.9590

Environment: SF cluster on Azure used for development

Description: My service fabric application is failing and in 'Error' state with 'Partition is below target replica or instance count.' All 5 nodes are stuck in 'InBuild' status and are show this warning in the SF explorer:
`'System.RAP' reported Warning for property 'IStatelessServiceInstance.OpenDuration'.
The api IStatelessServiceInstance.Open on node XXXX is stuck. Start Time (UTC): 2020-10-05 16:27:04.800.`

There are three service instance listeners on this application; one http listener for a web api, and two service bus listeners. The web app/listener seems to work for a few minutes, then all requests hang and are unresponsive.

I've tried to look through the cluster logs, but I haven't been able to uncover the issue. I'm looking for any troubleshooting tips to resolve this.

Attaching some log files from /Log/Traces in case that is helpful (whole directory was too large). Let me know what else would help.

OS(Windows/Linux):  Windows

---
Assignees: /cc @microsoft/service-fabric-triage
[log_traces.zip](https://github.com/microsoft/service-fabric/files/5334944/log_traces.zip)

**Comment by JustinKaffenberger** [comment]
Just to give you some insight, I ran into a similar problem. When I was opening my listeners, I was waiting on the result of an operation in the `RunAsync` method. As it turns out, `RunAsync` runs _after_ listeners are opened, so this caused a deadlock. 

So in short, keep an eye out for any logic that may be causing a deadlock due to the order of operations Service Fabric takes when starting a service. The lifecycle docs are [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-lifecycle).

**Comment by craftyhouse** [comment]
@kayoshino Please let us know if you are still facing this issue and looking for guidance.

**Comment by kayoshino** [comment]
@craftyhouse This issue is fixed. There was a sneaky line of code causing deadlock in my application. I was able to find and remove it which fixed the issue on node open. Closing issue.

**Comment by SaberZA** [comment]
Hey @kayoshino, I'm also experiencing this issue. Could you expand on what you did to fix it? Thanks!
