### ISSUE TITLE
Expedite support for .NET 5.0

### ISSUE THREAD

**Issue by juho-hanhimaki** [microsoft/service-fabric#1081]
Please consider expediting support for .NET 5.0. By the time SF 8.0 is planned to release .NET 5.0 has already gone through a noticeable period of its support lifetime and the focus in .NET ecosystem will be transitioning to the upcoming .NET 6.0.

.NET 5.0 surely didn't come by surprise. The release schedule [was announced](https://devblogs.microsoft.com/dotnet/introducing-net-5/) May 2019. First go-live (supported) version RC1 [was shipped](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/) September 13th 2020. I feel the SF team should have prepared for .NET 5.0 launch well in advance and released a supported version the same week as .NET 5.0 was released as has been done by some other Microsoft products such as Application Insights SDK.

Actually we had started developing .NET 5.0 services in September when the first production supported .NET 5.0 release was made. After it was [finally shared by SF team](https://github.com/microsoft/service-fabric/commit/dda0556f10ad7f6ba6cec050107b7fe249d95d55#diff-11a2f2909e655462f7c9f73fd72209711ea4a35e1c352203564e41213534529d) on November that support for .NET 5.0 is not planned [for a long time](https://github.com/microsoft/service-fabric/commit/195f1181b58b1b220ed2cac11e67f9d9c86b4170#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) I was shocked.

I think the importance of modern .NET needs to be re-evaluated by SF team. It really is where all the innovation is in the .NET space. Offering anything else than first class support is bad for customers and discourages investment in the use of product.

Also if you're a customer and .NET 5.0 support is important for you please let the team know it.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by mfmadsen** [comment]
.Net 5.0 support is important for us as well.

**Comment by WhitWaldo** [comment]
.NET 5.0 support is quite important for us, particularly because of the significant performance gains across the board that can be achieved with little else than changing the target framework and updating the relevant packages.

**Comment by LeroyK** [comment]
I'm quite surprised that Azure App Service gets support for .NET 5.0 at release time and Service Fabric doesn't. I have the feeling that Microsoft is winding down resources for Service Fabric. The releases contain only small features, [issues stay open for a long time](https://github.com/microsoft/service-fabric-services-and-actors-dotnet/issues/244), and this repo isn't up-to-date (having 2 year old code).

Are there currently any specific issues with .NET 5.0 on SF clusters?

**Comment by tuhland** [comment]
Adding my voice to this request. 

And I can also confirm, that the whole situation looks very much like typical MS moving on to the next new shiny. Which I've seen quite a lot in my time.

**Comment by WhitWaldo** [comment]
To be fair, on yesterday's community call, the Service Fabric team spoke to this issue and acknowledged that the ball had been dropped here. @masnider cited an internal API in .NET that was used to load libraries and hook things up that introduced a bit of a breaking change for Service Fabric support and has impacted their timelines. He spoke as well to the state of things on this repo, that work is done on another repo which is why pull requests aren't often accepted here. That continues to be a work in progress to migrate everything to work in the open.

A consistent theme from the team is that Microsoft has not been winding down any support for Service Fabric and that it does remain a priority as it's used internally by many of their customers.

@LeroyK I personally wouldn't recommend you do so, given that my local dev cluster started fielding all sorts of NotSupportedExceptions on the returns for Service Remoting calls per my issue [here](https://github.com/microsoft/service-fabric/issues/1079). A mere rollback to .NET Core 3.1 with no other changes resolved all the exceptions.

**Comment by vladislav-karamfilov** [comment]
Having SF 7.2 not supporting .NET 5.0 is affecting us too. We had the plan to migrate to .NET 5.0 by the end of next week (the main reason is being able to benefit on the perf improvements and some new APIs) but the news that SF 7.2 doesn't support it breaks our plan to pieces. I consider 7.1 as not supporting .NET 5.0 too (especially after what @WhitWaldo said about the internal API for loading libs). Please reconsider this - there will be many SF customers that need to upgrade to .NET 5.0 and this will be a major disappointment to not be able to do so in the near future.

**Comment by athinanthny** [comment]
@vladislav-karamfilov  @WhitWaldo  We have published [blogpost for latest 7.2 refresh release](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-72CU4.md#key-announcements) where we added Preview support for .NET 5 apps on Windows, GA timeline for Windows and finally when support for .NET apps on Linux in "Key Announcements" section. Release schedule page is also updated [here](https://github.com/microsoft/service-fabric#service-fabric-release-schedule).

**Comment by vladislav-karamfilov** [comment]
> @vladislav-karamfilov @WhitWaldo We have published [blogpost for latest 7.2 refresh release](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-72CU4.md#key-announcements) where we added Preview support for .NET 5 apps on Windows, GA timeline for Windows and finally when support for .NET apps on Linux in "Key Announcements" section. Release schedule page is also updated [here](https://github.com/microsoft/service-fabric#service-fabric-release-schedule).

This is great news, @athinanthny! We'll move back the migration to our plans and try it out as soon as we can. Do you have some estimate on the GA of the .NET 5.0 support? Will it be ready until the end of the year? Thank you very much for letting us know that we are now able to migrate!

**Comment by aL3891** [comment]
We're also in the process of moving to .net core 5, when adding `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` everything seems to work fine, but it's good that formal support is coming, even if its 6 months late. 

If we're being fair i think its also worth to point of that @masnider has been saying that exact same thing for years and years and this repo still doesnt even build on windows, updated code is posted months later, if at all, there are hundreds and hundreds of opens issues, with many with no response from the team and transparency on actual progress and what's being worked on is still basically zero.

They keep telling us to have patience, that they're working on making process changes, what their _ambitions_ are and that Microsoft totally isn't winding down service fabric support or development but (in)action speak a lot louder than words. Not to mention that even a basic timeline for these changes have yet to make an appearance.

Even if azure uses service fabric internally, (though the actual details of that are, of course, not ever elaborated on) it seems pretty clean what priority it has from a "customer" perspective.

**Comment by masnider** [comment]
@aL3891 we should probably move this to a separate issue but:

> though the actual details of that are not ever really elaborated on

What details do you think are missing? Microsoft won't talk about _every_ usage of SF, but some of the outlines that have been shared are pretty detailed, and it's not like there's been changes in how SF is used for eg SQL, CosmosDB, etc. 

Some recent examples:
https://www.youtube.com/watch?v=X-0V6bYfTpA&feature=youtu.be&t=3152
https://azure.microsoft.com/en-us/blog/azure-responds-to-covid19/ (sorry I can't link to a timecode in there but SF is called out within a discussion of the architecture of Teams)

>  but (in)action speak a lot louder than words. Not to mention that even a basic timeline for these process changes have yet to make an appearance.

Fair. Though hopefully folks are starting to notice improvement in responding to github issues as we ramp up the team there (though there was some backsliding during the holidays), including responding to older issues.  

There's clearly much more to do here, including getting better about communicating timelines around the OSS work. So far we have been focused on release dates for the actual product, release notes, and communicating roadmaps, and hopefully folks are noticing improvements there as well. 

The improvements to the OSS side are still something I am working through with the PM team to get a plan ackd and funded, so that remains behind where we want, but the other improvements _are_ being delivered, albeit much more slowly than we all would like.

**Comment by aL3891** [comment]
I'm referring to how service fabric is actually used, not that _is_ used. My point still stands, Microsofts actions regarding service fabric as a customer products speak a lot louder that words. Again, you've been saying this for literally years and now you're saying that the oss improvements aren't even "ackd and funded" yet? This almost to the day three years since open sourcing was announced? (https://techcommunity.microsoft.com/t5/azure-service-fabric/service-fabric-is-going-open-source/ba-p/791251) honestly, if you were a Microsoft external customer, how would you interpret that?

Bringing things back on topic, March is almost over and SF8 with the promised .net 5 support is no where to be found, no previews, no roadmaps, no tags in github, no blogposts covering high level goals, no reason why it was pushed back from its original November release date. I understand things can get delayed but then tell the community about it and why, don't just quietly update one line in the "roadmap" (again, a date and a version doesn't really a roadmap make)

So while i'm not saying nothing is being done as far as transparency and communication, i am sorry to say that not enough is being done and not in what i consider a reasonable time frame.

**Comment by 9527KGG** [comment]
**Service Fabric release schedule 
->
8.0 | 2021 Mar**

Today is **April 12th** now. Where do download version 8? Thanks

**Comment by juho-hanhimaki** [comment]
> **Service Fabric release schedule -> 8.0 | 2021 Mar**
> 
> Today is **April 12th** now. Where to download version 8? Thanks

Take a look at the [Service Fabric blog](https://techcommunity.microsoft.com/t5/azure-service-fabric/bg-p/Service-Fabric).

**Comment by dfedorth** [comment]
Looks like SF 8.0 supports .NET 5 on Windows hosts!

>Key Announcements
Support for .NET 5 for Windows is now generally available

Source: [Service Fabric 8.0 Release Notes](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_80.md#key-announcements)
