### ISSUE TITLE
Configure Windows security using a machine group - cluster creation fails

### ISSUE THREAD

**Issue by mcurko** [microsoft/service-fabric#1082]
Service Fabric Runtime Version: 7.2.413.9590

Environment: Standalone

Description: Trying to create a cluster and configure Windows security using a machine group as described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security#configure-windows-security-using-a-machine-group (using "Identity": "mons.hr\\mcurko" and "ClusterIdentity": "mons.hr\\cluster"). "cluster" group was created on AD, and the standalone server is a part of it. Attached JSON conf file is renamed to TXT.

Observed behavior: Cluster creation fails

Expected Behavior: Cluster creation to succeed

OS(Windows/Linux): Windows server 2016

If this is a regression, which version did it regress from? n/a
[SFDeployer-637414010696519748.trace.txt](https://github.com/microsoft/service-fabric/files/5568486/SFDeployer-637414010696519748.trace.txt)
[localhost.txt](https://github.com/microsoft/service-fabric/files/5568488/localhost.txt)
[ClusterConfig.Windows.OneNode.txt](https://github.com/microsoft/service-fabric/files/5568493/ClusterConfig.Windows.OneNode.txt)

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Hello @mcurko ,

In all three of these cases the root cause is related to active directory resolution. This one and the other two below
https://github.com/microsoft/service-fabric/issues/1084
https://github.com/microsoft/service-fabric/issues/1086

for example:
2020/11/19-16:44:36.421,Error,2112,SystemFabricDeployer.SFDeployer,   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
2020/11/19-16:44:36.421,Error,2112,SystemFabricDeployer.SFDeployer,   at System.Fabric.FabricDeployer.SpnManager.EnsureSpn()

It would be good to dig in to that deeper as that is blocking SF

This script may help validate some basics
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#validate-environment-using-testconfiguration-script

https://docs.microsoft.com/en-us/azure/active-directory-domain-services/troubleshoot may also help

Have you looked at the Azure SF offering to see if it's compatible with your needs? Just want to make sure you are aware of it.

**Comment by mcurko** [comment]
You have been quick in closing the cases. I'm trying to test various options in installing Windows standalone clusters, and I see that nothing works. One of the cases uses X509 certificate, how is that related to a domain? In another case adding the DC IP in the hosts file like this: `10.10.0.4 mons.hr` seems to resolve the problem, but I see this not as a resolution but rather as a hack for an unknown problem.

The documentation you're linking here points to a test script that I regulary run and the other one concerns errors on AD DS, none of which shows up in my test cases. I have spent days trying to dig out some useful information from the logs, but didn't find much. Why does SF complain `"mons.hr" ---> System.Runtime.InteropServices.COMException: The server is not operational.` when there's no such server (domain name controller is `mons-ds.mons.hr`).

I believe that the examples from the documentation and github should help us create starter SF clusters, from which we can explore further, but that's not the case, it's impossible to use them in any meaningful way.

**Comment by craftyhouse** [comment]
Why does SF complain "mons.hr" ---> System.Runtime.InteropServices.COMException: The server is not operational. when there's no such server (domain name controller is mons-ds.mons.hr). That's what is supported even further by your statement here "In another case adding the DC IP in the hosts file like this: 10.10.0.4 mons.hr seems to resolve the problem, but I see this not as a resolution but rather as a hack for an unknown problem." 

Essentially this is saying that the active directory can not be be resolved (the root of AD is mons.hr), not a particular host in the AD. Because of this it can not resolve identities. 

I'd recommend opening a support case to get assistance stepping through this with the right folks if you are still blocked on this as it doesn't look SF specific.
