### ISSUE TITLE
Cluster health monitoring

### ISSUE THREAD

**Issue by ksp2018** [Microsoft/service-fabric#110]
There does not seem to be any out-of-the-box cluster health monitoring options that come with Azure\OMS\Service Fabric Analytics. There seems to be a lot of options for monitoring applications themselves with custom coding, but what is the recommendation for cluster health monitoring at an enterprise level. 

Is it possible to get cluster health data into OMS?
What are the suggested metrics for health monitoring?
Can data from Service Fabric Explorer be aggregated into OMS?

**Comment by dkkapur** [comment]
Service Fabric exposes a set of events from the platform today that include health events for health reports emitted by various entities in the platform. On Windows today, these events are available via an ETW provider, through the operational channel - detailed, and the base operational channel as well in version >=6.2 (just being released at the time of this comment). Specifically:
1. Yes - via the operational channel. Modify the WadCfg in your cluster's ARM template based on this file (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad#log-collection-configurations) to include `4611686018427387912` as the `scheduledTransferKeywordFilter` if your cluster is below version 6.2. 6.2 onwards, the default setting should work.
2. Would be good to track % of time healthy, for an app, service, or node, since that may impact availability of your deployed workloads. I would also recommend setting up an alert if any nodes, cluster, or application goes unhealthy for more than 1min in your cluster. 
3. Health report data visible in SFX results in corresponding health events that can be pushed into OMS / Log Analytics. What other data would you like to see in OMS?

We're also working to bring the same experience to Linux in the near future.

**Comment by ksp2018** [comment]
Regarding #1, are there specific queries that you would recommend? Is the same level of data that is available via the REST API (https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-index) available via this logging?

**Comment by dkkapur** [comment]
I believe you get slightly less information than from the REST API, but you should have all the important bits (entity and health state), as well as info on the health report in there. I would suggest querying based on HM being the task for the event, i.e., with something like: `ServiceFabricOperationalEvent | where TaskName  == "HM"`

**Comment by ksp2018** [comment]
This answers my question - thank you
