### ISSUE TITLE
[Question] - running a managed identity application locally

### ISSUE THREAD

**Issue by furyd** [microsoft/service-fabric#1299]
I'm currently doing some investigative work around Service Fabric and Managed Identity, and when trying to deploy locally the deployment fails with "Application managed identity principalid cannot be null or empty", which I'm assuming is down to it being in a local environment.

Is there a way for it to be assigned to a local account when deployed locally? Or do I need to transform the applicationmanifest?

My ultimate aim is for a stateless web app to be able to use the AddAzureKeyVault extension for IConfigurationBuilder with Managed Identity, but falling at the first hurdle!

**Comment by levimatheri** [comment]
We have the `Principals` section Inserted by a config transform when deploying to Azure. For local we don't have the `Principals` declared. If you want to locally debug an application deployed to Azure with managed identity, you can use [Azure Service Authentication in VisualStudio](https://stackoverflow.com/a/52149006), and granting the necessary permissions to your user principal in Azure. You can use [`DefaultAzureCredential`](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to resolve the identity.

**Comment by francescocristallo** [comment]
> We have the `Principals` section Inserted by a config transform when deploying to Azure. For local we don't have the `Principals` declared. If you want to locally debug an application with managed identity, you can use [Azure Service Authentication in VisualStudio](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#authenticating-to-azure-services), and granting the necessary permissions to your user principal in Azure. You can use [`DefaultAzureCredential`](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to resolve the identity.

What tool are you using for config transform? I too need to add the Principals and Identities sections when deploying in production.
I tried  SlowCheetah but is not available for VS 2022.

**Comment by levimatheri** [comment]
@francescocristallo We use [this extension](https://github.com/sbabaei/Vsts/blob/master/ConfigTransformation/overview.md) in Azure DevOps

**Comment by craftyhouse** [comment]
In a future release the SF MI token service will be able to run in ‘standalone’ mode, so the application’s token acquisition flow would work locally as it would in the cloud. Watch release notes for this becoming available.
/cc @dragav

**Comment by huwjeffries** [comment]
@craftyhouse Is there any update on being able to configure MI token service to run in ‘standalone’ mode on Service Fabric? It's not great to have to update the ApplicationManifest.xml and ServiceManifest.xml files.

**Comment by dragav** [comment]
The change to make MITS run in standalone mode is done, although not included in the now-outgoing SF90 release. That may not be sufficient, though, for deploying apps locally with MI-like behavior. I don't have a timeline for that yet.

**Comment by huwjeffries** [comment]
Thanks for the update. We wouldn't expect the SF app to automatically pick up a managed identity when running locally. For other types of app we typically use code like this:
`
#if DEBUG
var tokenCredential = new ClientSecretCredential(configuration.TenantId, configuration.ClientId, configuration.ClientSecret);
#else
var tokenCredential = new ManagedIdentityCredential(configuration.ClientId);
#endif
var secretClient = new SecretClient(keyvaultUrl, tokenCredential);

`
i.e. When running locally we give it credentials (client secret) for a development managed identity so the code can still access azure resources. So long as we can do this trick with a local Service Fabric app we'll be happy.
Is this helpful at all?

**Comment by dragav** [comment]
Both ManagedIdentityCredential and [DefaultIdentityCredential](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) would work locally and in the cloud - when the environment is configured correctly. There is no need for ifdefs.

The problem, as you and others outlined above, is the application manifest. In a cloud deployment, the application resource declaration references a managed identity, which triggers a workflow to augment the app's manifest with the appropriate token endpoint - i.e. the resulting, actual app manifest will merge settings declared by you (under Principals) with the app-specific metadata from the SF Resource Provider. In a local deployment, there is nothing from which to generate this additional metadata, and so the validation of the Principals section fails. (Which then requires you to 'patch' the local manifest by removing MI references.)

Running MITS locally in standalone mode is one part of solving the development scenario; the next step is to address the app manifest generation problem described above.

**Comment by wumingcp** [comment]
According to my investigation, I find the application in the local Service Fabric runs under `network service` context, and the `network service` context doesn't share `Azure CLI` with the logon account context. This means when we run `az login` to log in with our account, it doesn't share the context with the application in Service Fabric.  

> Reference
> https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security
> By default, Service Fabric applications run under the account that the Fabric.exe process runs under. 

Here is a workaround
1. Download “Psexec” from https://docs.microsoft.com/en-us/sysinternals/downloads/psexec
2. Run the following command to start a PowerShell window under `network service` context
    ~~~ Powershell
    psexec -i -u "nt authority\network service" powershell
    ~~~
3. Run `az login` in the new PowerShell window, then you can use your account to local debug the application in service fabric.

Since local service fabric doesn't support managed identity, we still need to update the `ApplicationManifest.xml` and `ServiceManifest.xml`
1. Add a user in the application’s `ApplicationManifest.xml`. 
    ~~~ XML
    <Principals>
      <Users>
         <User Name="user" AccountType="NetworkService" />
      </Users>
    </Principals>
    <Policies>
       <DefaultRunAsPolicy UserRef="user" />
    </Policies>
    ~~~
2. Remove `ManagedIdentities` from `ServiceManifest.xml`

**Comment by alexey-aouslender-sp** [comment]
Hi @dragav, I am having the same issue as described above during deployment process. I am trying to release SF app with SystemAssigned identity defined from ADO to Azure and I am using ServiceFabricDeploy@1 ADO step. The step fails with the same error as mentioned above "##[error]Application managed identity PrincipalId cannot be null or empty." Patching the manifest is not an option for us, since we release into actual environment, do you have any recommendations for me how I can workaround this issue?

**Comment by dragav** [comment]
@alexey-aouslender-sp this thread is about deploying locally (for testing purposes); you seem to want to deploy an app to an Azure cluster directly? That is not the intent of MI - only apps deployed as Azure resources (via ARM/SF RP) can have managed identities. The app manifest is patched by the SF runtime as the deployment request arrives in the cluster - from the RP. 

If I misunderstood your scenario, please clarify what you intend to accomplish.

**Comment by alexey-aouslender-sp** [comment]
Thank you @dragav for your feedback, I was under impression that I can release an app with system assigned managed identity directly to the cluster. I checked the documentation and it clearly states that it only possible with ARM templates.

**Comment by kuxv** [comment]
@dragav hi, is there any way to enable VS login or AZ cli auth in local SF cluster? As the @wumingcp mentioned above the issue is the local SF cluster runs under Network Service account which cannot access the user's identity from VS or AZ cli. Unfortunately the workaround posted by @wumingcp does not work anymore as az login just fails in the powershell.
