### ISSUE TITLE
service-fabric-onebox fails on startup

### ISSUE THREAD

**Issue by snimmagadda1** [microsoft/service-fabric#133]
A build of the most recent image following this guide: 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac

results in the following failure on startup: 

```
docker logs sftestcluster
 * Starting OpenBSD Secure Shell server sshd
   ...done.
Drop folder path is set to '/home/ClusterDeployer/ClusterData'
Current machine IP Address is 172.17.0.2
Deleting old data root content
rm: cannot remove 'ClusterManifest.SingleMachine.Replaced.xml': No such file or directory
Setting environment for FabricHost & FabricDeployer to run
Running CoreCLR FabricDeployer on ClusterManifest.SingleMachine.xml
/home/ClusterDeployer/../FabricDrop/bin/Fabric/Fabric.Code/FabricDeployer.sh: line 23: dotnet: command not found
Error: FabricDeployer.exe failed
```

Any insights? (new to service-fabric)

**Comment by snimmagadda1** [comment]
seems to be these lines that failed? 
```
echo "Setting environment for FabricHost & FabricDeployer to run"
export LD_LIBRARY_PATH=${CodePath}

echo "Running CoreCLR FabricDeployer on ClusterManifest.SingleMachine.xml"
${CodePath}/FabricDeployer.sh /operation:Create /fabricBinRoot:${BinPath} /fabricDataRoot:${DataRoot} /cm:ClusterManifest.SingleMachine.Replaced.xml

if [ $? != 0 ]; then
    echo Error: FabricDeployer.exe failed
    exit 1
fi
}
```

**Comment by alexgman** [comment]
have you tried running CleanFabric.ps1 and try again?

**Comment by georgecooke** [comment]
Had this on Windows 10.

Issue is due to Debian/apt-get not wanting to install unauthenticated packages so the:

- dotnet-host 
- dotnet-hostfxr-2.0.6 
- dotnet-runtime-2.0.6

packages do not install and throw the following warning:

```
WARNING: The following packages cannot be authenticated!
  dotnet-host dotnet-hostfxr-2.0.6 dotnet-runtime-2.0.6
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

From within the same docker exec shell (bash) you can run the following to fix the issue:

`apt-get install -y --allow-unauthenticated dotnet-host dotnet-hostfxr-2.0.6 dotnet-runtime-2.0.6`

Whether or not we should be installing these unauthenticated packages is up for debate.

**Comment by maburlik** [comment]
This is an old issue and the container setup logic has been massaged since this generation of the release. Feel free to open another thread if you are still hitting issues.
