### ISSUE TITLE
[BUG] Recommended settings destroys the clusters

### ISSUE THREAD

**Issue by FredrikDahlberg** [microsoft/service-fabric#1342]
**Describe the bug**
The trouble shooting guide for SF in Azure states _"Additionally, the recommendation is to enable automatic OS image upgrade on Azure Virtual Machine Scale Set to keep your systems patched and secure."._ https://docs.microsoft.com/en-us/azure/service-fabric/how-to-patch-cluster-nodes-windows

When the image updates it breaks the clusters completely. I have yet not succeeded to recover from this.

**Area/Component**:
Infrastructure

**To Reproduce**
Setup up a cluster with a managed data disk in another location than C or D. Wait for OS image update.

**Expected behavior**
Mounted disk to stay at the same location. Updates to stop rolling out after node failures.

**Observed  behavior**:
Mounted disk changed from F to E causing the SF extension to fail. No way to manually change E back to F since it is not in the list.

**Service Fabric Runtime Version:** 
8.2.1571.9590 

**Environment:**
 - Azure
 - OS: Windows 2016

**Additional context**
I read some bloggers stating that it is not supported to have the datapath in other locations than the temp disk. I can not find this in the docs. The clusters have been up and running for years. What is the point of disk persistence with ephemeral disks anyway?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by inputoutputcode** [comment]
Automatic OS image upgrade by VMMS replaces the OS disk, the C drive. After this the reimage event causes all VM extensions a fresh install. The Service Fabric VM extension cannot run properly when the drive letter has changed because of DVD drive or something else. Because of this the drive letter to use managed disk should be something higher like "S". 
Temporary changing the drive letter via disk management should fix it, if the retries by the extension are not already exhausted.
The automatic OS image upgrade respects the upgrade domain concept, due to the extension error this should not bring down more than 20% of your cluster.

The old PowerShell script has been updated: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks#create-a-service-fabric-cluster-with-attached-data-disks

Please consider the VM extension support for managed disks: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-managed-disk

**Comment by FredrikDahlberg** [comment]
Thanks for the reply. Changing to the new script for preparing VM disks solves this problem for new clusters. Changing E: to S: for existing clusters permanently destroys them. I thought it would work since I could verify the datapath, the drive letter and the disk-script by remoting into to a node. But the nodes just went into reboot mode until they died. Every node.

**Comment by meenasaravanan02** [comment]
Hi @FredrikDahlberg, Check inputoutputcode's response.

#Please-close this issue

**Comment by FredrikDahlberg** [comment]
A redeployment of the cluster is the solution to this. Maybe the roll-out continues because the SF nodes show up as healthy first and then gets restarted.
