### ISSUE TITLE
[BUG] -Service Fabric SDK dont install in MAC M1 Processor (ARM64)

### ISSUE THREAD

**Issue by BetynMineiro** [microsoft/service-fabric#1348]
**Describe the bug**
The SDK doesn't install with vs studio or chocolatey when I use a virtual machine in mac book with an M1 processor

**Area/Component**:
Service Fabric SDK and runtime

**To Reproduce**
1. Install win in mac with m1 processor in parallels 
2. install vs studio 2022
3. create a project service fabric 
4. try installing service fabric with winpi or chocolatey

**Expected behavior**
SDK is installed and I can run a single cluster

**Observed  behavior**:

**Screenshots**

![image](https://user-images.githubusercontent.com/49888749/165748101-3361a85d-84b8-47e4-92c1-540ec6d10deb.png)

**Service Fabric Runtime Version:** 
ex: latest

**Environment:**
 - Parallels
 - OS: [Win 11] 

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by LeonWhelan** [comment]
Any follow up on this one? I'm having the same issue with my M1 Mac and the Service Fabric SDK in Parallels

**Comment by cmcfie** [comment]
Hi @LeonWhelan  and @BetynMineiro,

I see we are all trying the same thing and not getting far.

There seems to be several problems getting Azure Service Fabric SDK running on Mac M1 in Parallels using either Windows 10 or 11.

One problem is that you will see in the logs "Exception type: System.UnauthorizedAccessException, Message: Access to the path 'C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe' is denied.". This issue is discussed with a workaround by RetailPhil here (https://github.com/microsoft/service-fabric/issues/1336).

The next problem you may have if you are like me, is "Installing Driver: LeasLayr from C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys. Start Service call for driver failed LeasLayr because 0x800704fb". It seems 0x800704fb means ERROR_DRIVER_BLOCKED. I am guessing this means that this driver is not supported on ARM64.

If anyone can help sort this second problem I would be very grateful.

**Comment by BetynMineiro** [comment]
hi @cmcfie , I had the same problem with the LeasLayr and I find nothing that helps me to solve that.

**Comment by arimendelow** [comment]
has anyone made progress solving this issue?

**Comment by ChrisBurgessMS** [comment]
Are you using a x64 version of Windows or an arm version of Windows? If ARM version, we do not support ARM at this time. You need to install a x64 version for this to work.  I believe the reason why some of this works is because Windows has a x64 emulation for user mode but when running a kernel mode driver it needs to be compiled for ARM as no emulation is available.

**Comment by cmcfie** [comment]
> Are you using a x64 version of Windows or an arm version of Windows? If ARM version, we do not support ARM at this time. You need to install a x64 version for this to work. I believe the reason why some of this works is because Windows has a x64 emulation for user mode but when running a kernel mode driver it needs to be compiled for ARM as no emulation is available.

Hi @ChrisBurgessMS,

Thank you for your response. I think you will find we are all using ARM version of Windows, using Parallels as a VM platform. Is there any plans for Microsoft to build an ARM kernel mode driver? Especially as you announced Project Volterra which will be ARM.

**Comment by BetynMineiro** [comment]
yesterday I tried again, but I had the same problem as ever.

**Comment by ChrisBurgessMS** [comment]
> > Are you using a x64 version of Windows or an arm version of Windows? If ARM version, we do not support ARM at this time. You need to install a x64 version for this to work. I believe the reason why some of this works is because Windows has a x64 emulation for user mode but when running a kernel mode driver it needs to be compiled for ARM as no emulation is available.
> 
> Hi @ChrisBurgessMS,
> 
> Thank you for your response. I think you will find we are all using ARM version of Windows, using Parallels as a VM platform. Is there any plans for Microsoft to build an ARM kernel mode driver? Especially as you announced Project Volterra which will be ARM.
> 
> Even if Microsoft doesn't support ARM as yet, is there any advice on how we could compile it as ARM64?

I'm sorry.  I do not have any advice on how to compile the drivers to ARM64.

**Comment by joelvega** [comment]
I find it strange that 20% of the market is just completely locked out especially, as another has mentioned, Project Volterra. What this leads to is the dev kits for Project Volterra are not compatible with service fabric at all and there are 0 plans to implement it? I am completely baffled.

**Comment by wojtekf6** [comment]
any update?

**Comment by FreeBLD** [comment]
Tried installing the Service Fabric runtime. I can confirm that this issue still exists. Using an M2 MBP with Parallels and ARM version of Windows 11.

**Comment by thejvdagaang** [comment]
any update regarding this?

**Comment by jcotton42** [comment]
@olegsych Is there a ticket (preferably external, but internal will also suffice for me as an MS employee) that we could follow for updates?

**Comment by pavele** [comment]
> There are technical issues blocking this. We're already working on ARM64 support.

Do you have an ETA on that?
