### ISSUE TITLE
Is Standalone Linux clusters released?

### ISSUE THREAD

**Issue by rainryu** [microsoft/service-fabric#149]
Is Standalone Linux clusters released?

**Comment by mani-ramaswamy** [comment]
Not yet - stay tuned in the upcoming months.

**Comment by undecided2013** [comment]
+1, how far away/ETA? Can we start development on Linux assuming we will have a release for this in 2018?

**Comment by dkkapur** [comment]
We're looking at sometime in the fall for a public preview, and a GA to follow soon after. You will have a release for this in 2018! What is your intended cluster setup / infrastructure / configuration looking like? Trying to gather additional data for testing and validation. Thanks!

**Comment by undecided2013** [comment]
Thx Dk. We would be hooking SF to an existing infrastructure that is made up of Openshift pods hosting RHEL docker containers that contain JVM microservices that produce data onto Kafka topics. 
The intent is to have a partitioned service that pulls of the partitioned kafka topics with SF controlling the partition assignment instead of kafka doing it. We then want to utilize reliable actors for the proposed application. Let me know if you need more info. Thx again

**Comment by dkkapur** [comment]
@undecided2013 if you are still pursuing this, can you send me an email at deep dot kapur at microsoft dot com? Thanks!

**Comment by garrmark** [comment]
Any updates on the status of this, I have a linux standalone dev cluster running and would love to get a 3 node standalone cluster running, would it work now if i new the correct manifest settings?

**Comment by rainryu** [comment]
@mani-ramaswamy @dkkapur 

Any progressing  on this issues ？Thx

**Comment by dkkapur** [comment]
No updates yet, we still have some outstanding work on this front that is on the team's backlog, but not something we're prioritizing at the moment with work for Service Fabric Mesh and similar taking the precedence. We will get to it in the near future and keep you posted. If you have any context you can share on the scope of your deployment with me (deep.kapur@microsoft.com) that would be most helpful in getting a better sense of the requirements and various use cases. In the meanwhile - Ubuntu clusters on VMware or bare metal can be set up using the BOSH provider for SF: https://cloudblogs.microsoft.com/opensource/2018/12/04/announcing-service-fabric-provider-bosh/.

**Comment by maburlik** [comment]
The only variant of on-prem Service Fabric supported for Linux is through BOSH:
https://cloudblogs.microsoft.com/opensource/2018/12/04/announcing-service-fabric-provider-bosh/
https://github.com/starkandwayne/service-fabric-boshrelease
https://azure.microsoft.com/en-us/updates/deploy-service-fabric-ubuntu-clusters-on-premises-using-bosh/

Otherwise the primary and most stable form of running Service Fabric on Linux will be through Azure.

**Comment by MaChao9914** [comment]
Is there any specific plan for the release of Standalone Linux clusters?

**Comment by craftyhouse** [comment]
To respond to @MaChao9914 and keep this consolidated.
We do not have any specific updated plans outside of what was referred to above.  https://github.com/Microsoft/service-fabric/issues/149#issuecomment-669587037
There is no migration from Windows to Linux at this time - You'll have to setup a new cluster using BOSH and migrate the workloads accordingly.
