### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by FedericoBernardi** [microsoft/service-fabric#163]
Any plan to support Let's Encrypt in SF through Azure Portal? Since SF now supports the certificates by name would be amazing having a self renewal of the SSL Let's Encrypt wildcard certificate inside the portal and deployed  in the cluster

**Comment by WhitWaldo** [comment]
This is actually quite easy to do yourself now until this is more officially supported. I wrote a stateless service that utilizes [Certes](https://github.com/fszlin/certes) to create the orders based off an external table (with the latest expiration dates of each) that checks for new orders to run once a day and updates the certs based on where they need to go (since you may have a need to update certs elsewhere beyond Service Fabric too, like App Gateway).
