### ISSUE TITLE
Upgrade procedure for linux standalone clusters

### ISSUE THREAD

**Issue by daviddob** [microsoft/service-fabric#196]
What is the upgrade procedure for upgrading a SF linux cluster? 

I came across instructions here (Azure/service-fabric-issues#804) as well as an issue on the scftl repo (Microsoft/service-fabric-cli#52) however trying the upgrade via PowerShell fails on the register step with `"Fabric.exe was not extracted from the cab package"` although the file is present within the cab file (could be a windows vs linux binary issue). 

As far as using sfctl to do the upgrade it appears that several of the necessary commands are missing including ways to do the following. 

- Get-ServiceFabricRuntimeUpgradeVersion
- Copy-ServiceFabricClusterPackage
- Register-ServiceFabricClusterPackage

**Comment by suhuruli** [comment]
@maburlik

**Comment by maburlik** [comment]
For Linux, there are a different set of archive packages which need to be copied & registered within the cluster. The packages have 'deb' suffixes for Debian distros, and 'rpm' for RHEL.

**Comment by daviddob** [comment]
Is there a `sfctl` command (or series of commands) similar to `Get-ServiceFabricRuntimeUpgradeVersion` which lists the current versions and associated download links to pull down the `deb` or `rpm` packages?

**Comment by maburlik** [comment]
The cmdlet Get-ServiceFabricRuntimeUpgradeVersion was implemented as a query wrapper around the upgrade goal state file for our Windows standalone offering, since there arose a need for this to be publically queryable.

For Linux side, we don't yet offer a standalone equivalent so have not surfaced a public, convenient query mechanism for upgrade packages. There is a way of manually retrieving the packages by appending a consistent suffix onto the base download link:
http://download.microsoft.com/download/3/1/F/31F3FEEB-F073-4E27-A98B-8E691FF74F40/
such as
http://download.microsoft.com/download/3/1/F/31F3FEEB-F073-4E27-A98B-8E691FF74F40/ServiceFabric.6.3.119.1.deb
but you have to know the version you are querying beforehand. 

We are discussing the way to query the list of available package versions but it might require an Azure subscription. We will update the thread with details.



which could be used to publically retrieve the set of download links for packages, and

**Comment by maburlik** [comment]
@mhatreabhay
