### ISSUE TITLE
Event Store doens't work on standalone cluster

### ISSUE THREAD

**Issue by Shman4ik** [Microsoft/service-fabric#260]
I updated local cluster to 6.4.617.9590
add  on config
"addOnFeatures": [ "EventStoreService"  ],
and event store service doesn't work.
I see 2 Error in event Logs

Faulting application name: EventStore.Service.exe, version: 6.4.617.9590, time stamp: 0x5bf54461
Faulting module name: mscorlib.ni.dll, version: 4.7.3062.0, time stamp: 0x5ab95381
Exception code: 0x80131623
Fault offset: 0x000000000054c7e6
Faulting process id: 0x84c
Faulting application start time: 0x01d48b063002b5bf
Faulting application path: C:\ProgramData\SF\msk-dev-asf\Fabric\work\Applications\__FabricSystem_App4294967295\ES.Code.Current\EventStore.Service.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\b308b9c61f65cf2dfd876031ee385ba4\mscorlib.ni.dll
Report Id: 84bfefb1-bda5-4532-9ce0-418357750c46
Faulting package full name: 
Faulting package-relative application ID: 

Application: EventStore.Service.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: EventStore.Service.Exceptions.ConnectionParsingException: Config is Missing Operational Store Connection information
   at EventStore.Service.DataReader.EventStoreReader.<InitIfRequiredAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.DataReader.EventStoreReader.<SwitchModeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.EventStoreService.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__23.MoveNext()
Stack:
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

my cluster manifest
[ClusterManifest.txt](https://github.com/Microsoft/service-fabric/files/2639557/ClusterManifest.txt)

**Comment by suhuruli** [comment]
@srrengar

**Comment by srrengar** [comment]
@ibabou can you take a look at this?

**Comment by ibabou** [comment]
Hi Shman4ik,

The exception is happening as EventStore is trying to locate the tables storage configuration in the manifest, this is not needed if it is just a dev local setup.

Can you please change the following in the manifest:

  <Infrastructure>
    <WindowsServer>
      <NodeList>

to 

  <Infrastructure>
    <WindowsServer IsScaleMin="true">
      <NodeList>

In SingleBox setup, if multiple nodes are defined. IsScaleMin attribute is used by the system components to detect the initialization. Not only EventStore but other system services as well.

Thanks!

**Comment by Shman4ik** [comment]
Hi @ibabou,
I have a problem with standalone cluster, not with dev cluster on my machine.
This cluster hosted on 5 virtual machine.
I haven't tried to use EventStore on dev cluster yet.

**Comment by b47on** [comment]
The documentation mentioned in release notes (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-eventstore) says that "As of Service Fabric version 6.4. the EventStore APIs are only available for Windows clusters running on Azure only. We are working on porting this functionality to Linux as well as our Standalone clusters."

**Comment by ibabou** [comment]
@Shman4ik , Yeah, currently there is no support for standalone clusters as part of 6.4.

**Comment by raunakpandya** [comment]
Based on the comments above, closing the issue.

**Comment by xela30** [comment]
@b47on @ibabou Guys, how to remove that broken EventStoreService from the standalone cluster?

**Comment by ibabou** [comment]
Hi @xela30, what error are you seeing while trying to do the upgrade ? What is the rollback reason in this case ?

**Comment by xela30** [comment]
Hi @ibabou.
Thanks for quick turnaround!
I assume cluster config upgrade (to previous version with no EventStoreService) get's rolled back just because cluster is unhealthy due to broken EventStoreService.
Is there a way to determine the exact reason more precisely?
Get-ServiceFabricClusterConfigurationUpgradeStatus is not informative a lot.
I also tried ordinary Remove-ServiceFabricApplication (obviously with no luck).

**Comment by MattDarg** [comment]
Just to say I've also seen this issue.  As the local cluster runs the EventStore ok, I thought I'd try it on a DEV Standalone cluster.  

The config upgrade to turn on the feature worked- probably because the EventStore didn't error quickly enough, but the EventStoreService doesn't run (access denied trying to sue the LocalSystem account I think, which we're not running under).  

I tried to do another upgrade of the config to turn the EventStore off but this always fails as the Event Store Service is in error state.  Perhaps there's a way to manually force the config upgrade to go through, but as it's a DEV cluster it might be easier to re-install.

From the Event Log in case it's of interest:
LogonUser failed for SYSTEM. ErrorCode=E_ACCESSDENIED

__FabricSystem_App4294967295: Create user token: Account=SYSTEM, AccountType LocalSystem error = E_ACCESSDENIED

**Comment by ibabou** [comment]
Hi @xela30 @MattDarg,

I assume on this cluster you've UpgradeOrchaestrationService and using the following commands to get the settings and update it:

Get-ServiceFabricClusterConfiguration
Start-ServiceFabricClusterConfigurationUpgrade

If the service is in error state, the later command has arguments to set the error percentage allowed to make it through.

The access denied error will happen only if hosting on this machine is running under an account that can't start executables under LocalSystem, this shouldn't happen for a regular azure deployed cluster or even when you create a local setup through local cluster manager.

If  UpgradeOrchaestrationService is not installed in the cluster, the only other way I can think about, is doing a manifest only upgrade:

Get-ServiceFabricClusterManifest 
This returns the current manifest in xml, in order to be modified and having EventStoreService section removed.

Then upload the modified one (please increment the 'Version="X"', X here is the new version):-
Copy-ServiceFabricClusterPackage -Config -ClusterManifestPath <path_modified_manifest.xml> -ClusterManifestPathInImageStore NewClusterManifest -ImageStoreConnectionString "fabric:ImageStore"

and finally start a config upgrade:-
Register-ServiceFabricClusterPackage -Config -ClusterManifestPath NewClusterManifest
Start-ServiceFabricClusterUpgrade -Config -ClusterManifestVersion "X" -FailureAction Rollback -Monitored -ForceRestart

Note: Start-ServiceFabricClusterUpgrade also have parameters to tune error percentages.

Please let me know if you weren't able to get it removed through either of these ways.

**Comment by MattDarg** [comment]
Hi @ibabou, thanks for the reply.  

> The access denied error will happen only if hosting on this machine is running under an account that can't start executables under LocalSystem, this shouldn't happen for a regular azure deployed cluster or even when you create a local setup through local cluster manager.

Yes, I had this issue on an on-premise standalone cluster and we have the Host service running under a domain user account- which I guess it doesn't have LocalSystem rights (other system services run ok though),

As it was just a DEV cluster I ended up doing a cluster reinstall.  If it should work on a standalone cluster, given the right permissions, I might give it another go.  It would be useful to have the events easily available for developers and (once in production) our support team.

**Comment by xela30** [comment]
@ibabou Manifest only upgrade is also failing and rolling back. 
What do you think about upgrading it in UnmonitoredAuto mode as a last resort?

**Comment by xela30** [comment]
@ibabou Would you please advise if there is a big risk in running cluster manifest upgrade in UnmonitoredAuto mode?

**Comment by tomtoepel** [comment]
I've got exactly the same issue as you. Have you found a working solution to remove the EventStore ?

**Comment by xela30** [comment]
@tomtoepel I'm still waiting for answer from @ibabou as I don't want to accidentally screw up the cluster. Fortunately, unhealthy EventStore service doesn't block other applications from being upgraded. 
However, I assume the SF runtime upgrade will fail similarly to cluster config upgrade.

**Comment by xela30** [comment]
@ibabou JTR

**Comment by ibabou** [comment]
@xela30, sorry for missing the last message. can you please share the error you've been seeing after updating the percentage and trying out the change ? why did the upgrade failed in this case ? you can see in SFX -> Cluster -> Details -> Upgrade section what is blocking the upgrade while it is happening and what is the last upgrade failure reason.

**Comment by b47on** [comment]
I can only confirm, that I found no way to remove the event store, just reinstalled the cluster (luckily I tested it on a dev cluster)

**Comment by xela30** [comment]
Hi @ibabou ! Thank you for looking into this again. Here is the screenshot:
![image](https://user-images.githubusercontent.com/3661403/54425197-696ebf00-471d-11e9-8eff-f5a30d78a805.png)

**Comment by xela30** [comment]
Hi @ibabou . Thank you for looking into this again. Here is the screenshot:
![image](https://user-images.githubusercontent.com/3661403/54428313-c8383680-4725-11e9-9fda-87ee4070248a.png)

**Comment by ibabou** [comment]
@xela30 I doubled checked with failover team. and it appears that there is no way an upgrade will go through if it is monitored. healthcheck will always fail because one of the system services is in error with no quorum. so you'll need to use unmonitoredauto while doing this upgrade.

**Comment by xela30** [comment]
@ibabou Got it, thanks! 
Does anybody from the team know if running such kind of configuration upgrade (I mean with EventStore service removed from it) will actually remove the service and don't put the cluster into unpredictable state?

**Comment by querbyte** [comment]
Are there any additional information or a way to remove the broken Event Store Service from the cluster? I have the same problem and tried to find a solution without reset the whole cluster.

**Comment by suhuruli** [comment]
@ibabou , can you share instructions on how to remove Event Store service safely?
