### ISSUE TITLE
VSTS agent claims Service Fabric SDK is not installed on the build agent

### ISSUE THREAD

**Issue by macgyver2k** [Microsoft/service-fabric#268]
I tried to deploy a Service Fabric application to a local dev cluster via a VSTS agent with standard VSTS Service Fabric app deploy task, but it failed claiming not beeing able to find Service Fabric SDK installed on the agent.

`##[error]Service Fabric SDK is not installed on the build agent.  Go to https://aka.ms/servicefabric to download and install it.`

The agent was installed on a fresh Windows Server 2016 Datacenter.
Before the agent, I installed the newest SDK via WebInstaller and created a single node cluster via local cluster manager.
The agent is running under network service account.

I also found this to be failing on a Windows 10 VS2017 Enterprise Evaluation VM.

**Comment by bishal-pdMSFT** [comment]
We use registry keys to look for SDK. This error can happen when 32 bit agent (released recently) is installed and then it wont find the registry key in 64 bit registry hive. The fix is to use 64 bit agent.

This could also happen if you have started agent before installing SDK. If so, you need to re-start the agent.

BTW, the task checks for following registry key to decide if SDK is installed:
HKLM:\SOFTWARE\Microsoft\Service Fabric SDK
