### ISSUE TITLE
Start-ServiceFabricClusterConfigurationUpgrade not working

### ISSUE THREAD

**Issue by rpili1313** [microsoft/service-fabric#278]
Hi,

I have an on-prem SF cluster running with certificates. When I try to change the config.json and run the command: Start-ServiceFabricClusterConfigurationUpgrade

It does not seem to trigger an action. I do not get any errors and when I run: Get-serviceFabricClusterConfigurationUpgradestatus it outputs: 
RollingForwardCompleted 

Already running of the node itself so... Any more suggestions?

Kr,
Roberto

**Comment by originalnoe-nazvanie** [comment]
Hi, there is a documentaion about on-prem cluster manifest upgrades.
shortly:
1) Connect to sf cluster 
 Connect-ServiceFabricCluster -ConnectionEndpoint d1v6-sf.domain.lan:19000 -KeepAliveIntervalInSec 10 -X509Credential -ServerCertThumbprint publicsslthumprinthere -FindType FindByThumbprint -FindValue youraccesscertthumbprint -StoreLocation CurrentUser -StoreName My
2) get old config 
Get-ServiceFabricClusterConfiguration >> .\1.0.61.json
3) create new one from old one
Copy-Item  .\1.0.61.json  .\1.0.62.json
4) make changes in .\1.0.62.json, for example add new node and change version to new one (1.0.62 in my case)
5) start config upgrade
Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\1.0.62.json -MaxPercentDeltaUnhealthyNodes 30 -MaxPercentUnhealthyApplications 30 -Debug
6) check upgrade status 
Get-ServiceFabricClusterConfigurationUpgradeStatus
7) when the upgrade complited you'll see 
RollingForwardCompleted            some_iteration_number 1.0.62

**Comment by JustinKaffenberger** [comment]
I'm having the same problem. I make a small upgrade, such as increasing the port range of my primary node type, upgrade the version number, and then run `Start-ServiceFabricClusterConfigurationUpgrade` with the new configuration file.

When I run `Get-ServiceFabricClusterConfigurationUpgradeStatus` it does not indicate that any upgrade attempt has been made.

**Comment by lanfeust69** [comment]
I had the same kind of issue. Apparently, `Start-ServiceFabricClusterConfigurationUpgrade` doesn't bother reporting errors happening on the cluster.

In my case, this was related to issue MicrosoftDocs/azure-docs#38623.

Note that changing the json was not enough : although the incorrect one had not been deployed, the entry in the store was associated with the `clusterConfigurationVersion`, which I had to change in the json sent (else same silent error). When I managed to send a json that would actually trigger a config upgrade, it still had problems (the direct issuer of a certificate was an intermediary not explicitly listed, and the remainder of the chain is not checked ; at least this part is mentioned, if not obvious), which I could fix only by hacking the generated xml directly on the nodes : no rollback either automatic or manual is available.

All in all not the smoothest experience...

**Comment by MicahMcKittrick-MSFT** [comment]
@dkkapur @peterpogorski @masnider

**Comment by JustinKaffenberger** [comment]
Something is quite wrong with the configuration upgrade system. For me, it all started with [this issue](https://github.com/Azure/service-fabric-issues/issues/1512), in which case Service Fabric was incorrectly erroring on the configuration that it returned to me. Once I removed the empty `WindowsIdentities` element from the configuration that Service Fabric returned to me, I was able to get past the exception, but now `Start-ServiceFabricClusterConfigurationUpgrade` just no-ops, which I describe in more detail in [this issue](https://github.com/Azure/service-fabric-issues/issues/1572)

In my case I have a very simple X509 secured cluster that I'm essentially screwed with. I can't upgrade anything about the cluster, whether that be increasing my `ApplicationPorts` range or trying to enable a new Service Fabric optional feature.

I have an Azure support ticket open for this, but I would love to get movement on this since I've been stuck for 3 months now.

**Comment by maburlik** [comment]
Changes have been made to FabricUOS targeted for the next release 7.2 to rework the way upgrades are managed in FabricUOS to ensure better state consistency, improve internal retries, and to provide considerably better transparency into errors encountered during the initial and ongoing processing of upgrades. Part of the change was targeted specifically to avoid silent failures as you have described in this thread.
