### ISSUE TITLE
Building with CentOs: 404 The specified blob does not exist

### ISSUE THREAD

**Issue by phudtran** [microsoft/service-fabric#334]
Getting a 404 when building with CentOs

https://sfprebuilt.blob.core.windows.net/binaries/WinFab.Linux.Libs.2.4.1-centos.nupkg

<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:35e28e2e-601e-0050-5e82-124ac9000000 Time:2019-05-24T22:46:09.6220063Z
</Message>
</Error>

**Comment by bpm-ms** [comment]
Uploaded the missing package.  Should be fixed!

**Comment by phudtran** [comment]
Thanks!

**Comment by 404-xianjin** [comment]
hello
I deployed the service fabric on my local Centos 7 1908, and executed ./runbuild.sh -centos in the /root/service-fabric directory. When the progress reached 89%, the following fault code would pop up:

clang-5.0: error: unable to execute command: Killed
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 5.0.0 (https://github.com/GorNishanov/clang.git a7b79f4b65825ad3c0da0aae7b15c95fac7624f6) (https://github.com/GorNishanov/llvm.git f3e85a45cfc3745f0db04cfeeee892c463e30e7b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-5.0/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: note: diagnostic msg:

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-5.0: note: diagnostic msg: /tmp/StoreStateProviderFactory-7aba2c.cpp
clang-5.0: note: diagnostic msg: /tmp/StoreStateProviderFactory-7aba2c.sh
clang-5.0: note: diagnostic msg:

make[2]: *** [src/data/tstore/lib/CMakeFiles/objects_TStore.dir/__/StoreStateProviderFactory.cpp.o] Error 254
make[1]: *** [src/data/tstore/lib/CMakeFiles/objects_TStore.dir/all] Error 2
make: *** [all] Error 2
Error: cmd failed: make

Can you take a look for me? thanks
