### ISSUE TITLE
Missing Microsoft.ServiceFabric.Data.Extensions nuget update

### ISSUE THREAD

**Issue by negberts** [microsoft/service-fabric#344]
There is no update for the Microsoft.ServiceFabric.Data.Extensions package in nuget and therefore upgrading to 6.5 is not possible because the package has a constraint Microsoft.ServiceFabric.Data.Interfaces (= 3.3.664)

**Comment by amanbha** [comment]
@negberts This is a known issue caused by nuget package versioning of Microsoft.ServiceFabric.DAta.Extensions, we will release updated nugets soon.
As a  workaround:
If you are using older style of .csproj and it has packages.config., You can delete the entry for Microsoft.ServiceFabric.Data.Extensions and try updating the nuget packages again.

If its a newer style project and you don't have packages.config in it:
-  If its an Actors project, downgrade Microsoft.ServiceFabric.Actors to 3.3.638 and then upgrade to latest version.
-  If its a Services project, downgrade Microsoft.ServiceFabric.Services to 3.3.638 and then upgrade to latest version.

**Comment by jspuij** [comment]
When is soon?

**Comment by amanbha** [comment]
@jspuij WE encountered some issues during the final testing of the refresh release which pushed it out a little bit. ,ETA is around 2 weeks.

**Comment by amanbha** [comment]
The updated packages are now uploaded to nuget.org
https://www.nuget.org/packages/Microsoft.ServiceFabric.Data.Extensions/3.4.658

**Comment by jspuij** [comment]
Thank you!
