### ISSUE TITLE
Constructive criticism

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#372]
I'm really trying to be constructive here, but the level of communication from the Service Fabric team is getting worse. 6.5.658.9590 is available in the portal. There's a new SDK. There are posts here which have not been responded to. Something has got to change.

**Comment by andrewtyped** [comment]
After some sleuthing, I have news. The team is communicating at least as well as before, maybe a little better - but many of us didn't know about it because the team blog has been quiet since July 4. As a dev who looked mainly to the team blog for his SF news, I could be forgiven for thinking the silence was a bad sign. I think an update there to announce the cut-over of communication to a new medium, if that is the intention, would help a lot.

In the [latest community Q&A](https://www.youtube.com/watch?v=3bqRtvdEEhM), the team mentions a shift of their content platform to Microsoft Docs. You can find release notes [here](https://docs.microsoft.com/en-us/azure/service-fabric/release-notes). This page has been updated since June. There is even a [roadmap](https://azure.microsoft.com/en-us/updates/?product=service-fabric) (this was also added to the README of this repo ~2 months ago). 

Can't offer a defense on issue response rates though - really seems like a coin flip as to whether or not a given issue will see a response, however well researched. On the bright side, [paid support](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support) is an option.

**Comment by maburlik** [comment]
Please tune into the upcoming community Q&As to get visibility on the items we are currently tracking and share your feedback. You can suggest topics to be addressed in these sessions at this link: https://aka.ms/sfcommunityideas

For more urgent matters you can create a ticket through the Azure portal. Closing for now but feel free to create another thread if you have further comments or topics to discuss.
