### ISSUE TITLE
Backup/Restore Access Denied in secured cluster using common names

### ISSUE THREAD

**Issue by Kisox** [microsoft/service-fabric#460]
Hi,

i have a secure cluster that uses common names to identify the server/client certificates. I now wanted to enable the BackupRestoreService by adding

`    "addOnFeatures": [
      "DnsService",
      "BackupRestoreService"
    ]`

to my cluster config file.

When i now open the service fabric explorer, i get an "Access Denied" error message. It fails to get backup restore policies. Same error message pops up when i browse through my applications.

As the backup restore service worked in a dev cluster, i looked for some differences and saw that the dev cluster configuration uses thumbprints instead of common names. So i changed that and it works.

For easier rollout of certificates i would prefer using the common names though.

Thanks for listening!

**Comment by athinanthny** [comment]
Thanks for feedback and Glad to know your issue is resolved.

**Comment by sladeedmonds** [comment]
@athinanthny 

So I just encountered this same behavior.  I'd deployed a cluster initially using thumbprint-based certificates and then switched it over to a Common Name based deployed by following the documentation.  The cluster successfully switched over to the Common Name certificate, but the BackupRestoreService was broken as a result.  Anything at all I tried to do in SFX that had to do with backups failed with Access Denied errors and, after successfully authenticating to the cluster with the Connect-SFCluster cmdlet, attempting to do anything with backup and restore cmdlets failed with authorization errors.

I re-deployed the cluster from scratch and BackupRestoreService seems to be working just fine, **and** the cluster was deployed using Common Name certificate.  So the cluster config still references the certificate thumbprint, but the cluster itself is using Common Name. 

Please explain any known limitations or guidance in regards to switching a cluster from Thumbprint-based deployment to Common Name based deployment as it relates to the BackupRestoreService, or just any guidance at all using the BackupRestoreService on clusters using Common Name certificate deployments.  It would be helpful if there was documentation that clarifies the expected behavior and/or any known limitations.
