### ISSUE TITLE
Test-ServiceFabricApplicationPackage Fails Due to Method Not Found Error

### ISSUE THREAD

**Issue by aresowj** [microsoft/service-fabric#557]
```
Test-ServiceFabricApplicationPackage
cmdlet Test-ServiceFabricApplicationPackage at command pipeline position 1
Supply values for the following parameters:
ApplicationPackagePath: X:\SomePath\App\
Test-ServiceFabricApplicationPackage : Method not found: 'Void System.Fabric.Management.ImageBuilder.ImageBuilder.ValidateApplicationPackage(System.String, 
System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
At line:1 char:1
+ Test-ServiceFabricApplicationPackage
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Test-ServiceFabricApplicationPackage], MissingMethodException
    + FullyQualifiedErrorId : System.MissingMethodException,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
```

I was not updating my SDK on the machine, but it just fails with this error while it was working fine. I can upload and deploy the package if I do it manually with `Copy-ServiceFabricApplicationPackage` and `Register-ServiceFabricApplicationType` on the cluster.

After seeing this error, I tried to uninstall every SF stuff and reinstall the SDK with WebPlatform PI. However it did not help.

What am I missing here?

**Comment by jagilber** [comment]
fwiw i was able to reproduce same issue until i used web platform installer to upgrade service fabric sdk version from 3.1 to latest (currently 4.1.409)

**Comment by maburlik** [comment]
Method not found issues are caused by out of sync version dlls being loaded by the same process, and is usually the result of old dlls remaining in GAC or if the current executing directory is mismatched against the SF installation.

In the future if you hit similar issues you can identify the sources of loaded dlls using Fusion Logs:
https://techcommunity.microsoft.com/t5/iis-support-blog/fusion-log-viewer-fuslogvw-exe/ba-p/784396
https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer
