### ISSUE TITLE
AggregateException on Start-ServiceFabricClusterConfigurationUpgrade

### ISSUE THREAD

**Issue by mispencer** [microsoft/service-fabric#656]
I attempted to run `Start-ServiceFabricClusterConfigurationUpgrade` on in-premise production cluster today and received the error below. I then downloaded the current cluster configuration (using ` Get-ServiceFabricClusterConfiguration`), updated the config version, and attempted `Start-ServiceFabricClusterConfigurationUpgrade` with that current configuration but I received the same error.

I have been able to run `Start-ServiceFabricClusterConfigurationUpgrade` in past as recently as the last few days. We just upgraded to SF version 6.4.622.9590 as of today. We also added new two nodes to cluster today (thus the attempted configuration update). 

As this error message is generic, I am unsure what to attempt from here. Is there any way to receive more information on what is failing or any known resolution to this issue we are experiencing?

```
VERBOSE: System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65
   at
System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyn
cOperationContext context)
   at
System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationCo
ntext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean
 expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath C:\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa
   ...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterC
   onfigurationUpgrade
```

**Comment by maburlik** [comment]
I'll try to address the distinct issues.

@mispencer To get full information regarding aggregate exceptions when calling Start-ServiceFabricClusterConfigurationUpgrade, run:

```
try {(Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\config2.json )} catch { Write-Host $_.Exception.ToString(); }
```

@b47on I'm not too familiar with the policy of changing ports in the node type but the safer approach here would be to recreate the cluster when deciding to change the port range in order to avoid unexpected disruptions. We would need additional logs from the cluster to determine why the cluster did not come up.

In regards to the desynchronized manifest version I expect an internal failure was hit in FabricUOS which resulted in this desynchronization. I've made changes to the state management pattern as part of a change targeted for 7.2 in FabricUOS to ensure more consistent behavior and avoid hidden failures like these.

@Adebeer The changes mentioned above would also expose the explicit reason for failure you had encountered.

@mispencer Regarding your comment related to AddNode.ps1 compatibility with clusters running gMSA this appears to have been a bug which I have also fixed as part of the incoming FabricUOS changes. With the new behavior if AddNode had already been run, the added delta node in the new config will be automatically recognized as added as opposed to resulting in an internal failure. For 7.1 and earlier clusters running gMSA, nodes should not be added via AddNode.ps1, but only via cluster config upgrade.

@chenzuo The security section conflict you are hitting was fixed in 7.0 CU4.

If anyone has further issues please create a new issue since this thread is discussing multiple distinct issues.
