### ISSUE TITLE
Service Fabric is not Working with the new Firewall in Windows

### ISSUE THREAD

**Issue by paule96** [Microsoft/service-fabric#74]
Hello Community,

the Windows Server 2019 Preview have some changes to the firewall service in windows. It's now called Windows Defender Firewall and not Windows Firewall. This is a Problem for the Script ```.\TestConfiguration.ps1``` form the ["setup your own cluster documentation"](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-standalone-cluster#validate-the-environment).
It would be nice to hear when the first working bits for windows server 2019 are out there.
Currently it says this: ```Querying Windows Firewall service status on machine localhost resulted in exception: Object reference not set to an instance of an object..``` 

Metadata:
- Windows Version: Windows Insider-Preview Server vNext en-us 17623
- Service Fabric Version: Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494

Hope this issue helps. :)

**Comment by vturecek** [comment]
@maburlik do you know if anyone has started looking at this in WinServer 2019?

**Comment by maburlik** [comment]
The name in trace "Windows Firewall" is just used for user familiarity and is not the query name. It's actually querying MpsSvc service status. There was an issue with this in RS4 because the service name casing had changed from MpsSvc to mpssvc, and has been fixed on our end to be case-insensitive by @alsantam. Alfredo which version has the fix? We will be releasing 6.2 soon, does it have this fix?

**Comment by alsantam** [comment]
Yes this fix is in 6.2
