### ISSUE TITLE
CryptAcquireCertificatePrivateKey failed. Error:0x80090014

### ISSUE THREAD

**Issue by AndriyGorda** [microsoft/service-fabric#773]
Hello team,

Could you please provide a fix or suggest a workaround? We are blocked for 2 days already.

Since May 10 our Azure clusters are down with nodes been unable to read private key from certificate.
Since January 2018 they were working without issues.
The certificate is the same as before, was not changed and currently present on the nodes, with private key in it. 
Recreation of cluster from the scratch leads to the same error.
Also recreation of cluster with previous Service Fabric version in ARM template leads to the same error as well.

Node event log has such errors and warnings as:

- Can't get private key filename for certificate. Error: 0x80090014
- CryptAcquireCertificatePrivateKey failed. Error:0x80090014
- Can't ACL FileStoreService/SecondaryAccountNTLMX509Thumbprint, ErrorCode E_FAIL
- SetCertificateAcls failed. ErrorCode: E_FAIL
- Failed to get private key file. x509FindValue: 406193559C7123964B309347720A3D3D5CD6EF2A, x509StoreName: My, findType: FindByThumbprint, Error E_FAIL

This seems to relate to https://github.com/Azure/service-fabric-issues/issues/235.

Thank you in advance,
Andriy

**Comment by craftyhouse** [comment]
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/tree/master/Security#category has updated guidance here https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Security/Create%20a%20New%20Self%20Signed%20Certificate.md

**Comment by johnc-ftl** [comment]
It's great that there's finally a guidance article on this, but shouldn't SF Windows support CNG certs? The bug still exists, or the feature to support the more recent version of the Windows Crypto API is still missing.

Is there a separate issue tracking this (that is publicly visible)?

**Comment by juho-hanhimaki** [comment]
I think CNG certs still don't work with SF. I hope the CNG support would be implemented to SF.

**Comment by johncrim** [comment]
I'm commenting on this closed issue in the interest of helping others, since the (previous) problem with CNG certs doesn't seem to be documented anywhere else:

From my testing yesterday and today, it appears that CNG certs can NOW be loaded by Service Fabric 10.0.1816.9590 (Windows only). I had to add the ACL so that the NETWORK_SERVICE group can access the cert private key file, as @dragav described above.

I should qualify this by saying that I only verified that `<SecretsCertificate ...` can be used with CNG certs, and the encrypted config is successfully decrypted. I have not verified that other types of SF certificates work properly with CNG certs.

This is very nice because we can now remove our [special handling of SF certs](https://stackoverflow.com/a/58926479/605067) to ensure that the private key isn't stored by the "Microsoft Software Key Storage Provider" when they are created and installed.
