### ISSUE TITLE
Service Fabric AppTypes accross multiple solutions

### ISSUE THREAD

**Issue by haseeb-ahmed-tkxel** [microsoft/service-fabric#917]
Hi,

Hope you all are fine. I was facing a issue with Service Fabric that some of you might have faced as well. Right now, the project that I'm working on is structured so that all the micro-services are in there own solutions. Working with Service Fabric, that doesn't seem possible since all AppTypes should be in the same solution as the App.

Any ideas if this can be done? I'm wanting this because if all the projects are in a single solution, that means more loading time for the solution, more build time, larger repo download and etc.

Looking forward to your help.

**Comment by compgumby** [comment]
I'm in the same boat here. I have a large-ish SF solution that I'd like to split up. I guess I don't fully understand how to take this out-of-the-box VS solution and convert it to multiple solutions that somehow get stitched together through DevOps. We are using DevOps and I see there are build pipelines, but I am really more interested in focusing on my business objectives rather than having to do a deep dive into a bunch of docs, blog posts and examples that don't actually do what I'm trying to do to figure out how to achieve this - what has to be - common scenario. I can't imagine people out there using SF with 50+ projects haven't split up what they're doing. And yet - I can't find anything I can just "grab and go". 

I'll do it if I have to, but if anybody has any decent resources surrounding this, I'd love a link.

**Comment by tuhland** [comment]
Without knowing more about your project this sounds more like an architecture issue than an SF issue. You should aim to have multiple applications that can be built and deployed independently.

We're far from that as well. We currently have a solution with 120+ projects in them, but it contains 7 different SF applications. I've split it up into 7 solutions, but everybody uses the slow big one out of laziness.

But during the build and deployment process, the solutions don't even get used. It is the applications that get built and deployed. No solutions involved. We wrote a simple PowerShell script that builds all the projects  referenced in the .sfproj file (basically the applications dependencies), and the next build steps then build and package the application itself.

**Comment by compgumby** [comment]
@tuhland - Thank you for the quick response. This is surely where I have a blind spot. I have a good sense of how I'll be splitting the solution, and I even have a notion of how we might have multiple SF applications, but I don't yet have a level of comfort regarding how SF apps might communicate with each other (if there's some special something required) and I don't have a good handle on what makes an SF app an SF app. Now that I hear you're not even using the solution file but doing it all through scripts, it's changed my focus a bit and I'm beginning to catch on at least with respect to deployment. 

Time for a proof-of-concept project or two to see how this all plays out - hoping to stitch it all together in an Azure pipeline.

Thanks again. :)
