### ISSUE TITLE
System Assigned Managed Application Identity's principal is not found

### ISSUE THREAD

**Issue by gheibia** [microsoft/service-fabric#927]
This seems to be a bug.

**Cluster Version**: 7.0.470.9590

Deployed an application through ARM which is configured with a System Assigned managed Identity. After deployment, I can see through both Azure Resource Explorer and SF's Explorer dashboard that the application is deployed successfully. I can also see (in ARE) that a "PrincipalID" is created for the application. However, I can't find the service principal anywhere to for example, assign a role to it.

When this preview feature was introduced and I tested it, I could find the SP object in portal in the list of "Enterprise Applications". The object was named after the cluster ("cluster-name/applications/app-name"). Updated documentation however, seems to suggest that the portal integration for SA identities is not available:

[https://docs.microsoft.com/en-us/azure/service-fabric/how-to-grant-access-other-resources](https://docs.microsoft.com/en-us/azure/service-fabric/how-to-grant-access-other-resources)

> Support for system-assigned Service Fabric managed identities does not include integration in the Azure portal; if your application uses a system-assigned identity, you will have to find first the client ID of the application's identity, and then repeat the steps above but selecting the Azure AD user, group, or service principal option in the Find control.

And I indeed can't find the object in AAD anymore.

I tried Powershell and no luck either:

`Get-AzureADServicePrincipal -ObjectId "*************************f1030a8"`

```
Get-AzureADServicePrincipal : Error occurred while executing GetServicePrincipal
Code: Request_ResourceNotFound
Message: Resource '*************************f1030a8' does not exist or one of its queried reference-property
objects are not present.
```

**Comment by jberezanski-mdg** [comment]
We are using System Assigned MIs for our SF apps and everything works as expected from AAD side:
- the Service Principals are named `cluster-name/applications/app-name`
- they are visible in the Portal -> AAD -> Enterprise Applications (with Application Type filter set to All) and they can be found by normal name prefix search
- they can be obtained with `Get-AzureADServicePrincipal` via `-ObjectId ...` (where ObjectId is shown e.g. in the SF Explorer as "Principal Id") or by name (`-SearchString ...`)

We are running SF 7.1, however (to be precise: 7.1.417.9590).

The docs statement "Support for system-assigned Service Fabric managed identities does not include integration in the Azure portal..." seems a bit misleading, because those principals can be located just fine using normal name search with the principal type filter set to the generic "Azure AD user, group or service principal" (in fact, they do not show for me when searching by ObjectId or client id/AppId). I suppose what the docs meant to convey was that there is no dedicated principal type filter for "Service Fabric applications" which would show those principals only.

**Comment by gheibia** [comment]
Thanks. Things have evolved quite a bit since I opened this. I haven't checked the documentation, but we not only see the service principals in portal, we can add them to groups or use them along with RBAC.
