### ISSUE TITLE
Custom fabric settings - How to read?

### ISSUE THREAD

**Issue by jackbond** [Microsoft/service-fabric#93]
In the portal page for a fabric, there's a tab for "Custom Fabric Settings". It's straight forward to add one, but I haven't been able to find any documentation on how to read that value programmatically. I apologize if I've missed something obvious, but could someone provide a pointer? Thanks.

**Comment by bpm-ms** [comment]
@anmolah who would know about this?

**Comment by rishirsinha** [comment]
@jackbond 
The fabricsettings is merged into cluster manifest. Get-ServiceFabricClusterManifest and its various incarnations can be used to get the cluster manifest.

**Comment by masnider** [comment]
@jackbond just in case this wasn't clear - in the portal you're configuring the cluster. The settings you would put there are cluster level configuration and are used to configure things not first-classed in the portal. So for example you can configure node types and capacities in the cluster setup in the portal, but there are many other settings that you can't (all are listed [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings)). The "custom settings" lets you define these, and as Rishi said they get merged into the total cluster settings. There's no specific API to read them individually (other than getting the whole generated cluster manifest/settings) because they're usually not useful for the applications. Hopefully this answers your question. I'm going to close down this issue. If you find this answer isn't sufficient feel free to reopen it or open another issue.
