### ISSUE TITLE
Service fabric onebox still installs version 7.1 in top of Ubuntu 16

### ISSUE THREAD

**Issue by jfalameda** [microsoft/service-fabric#950]
Service fabric onebox still installs version 7.1 in top of Ubuntu 16. As I read on other threads it was said that version 7.1 supports ubuntu 18.04 and that soon it will be deployed to the docker repository.

I just checked today and it still installs over ubuntu 16. I cannot find any instructions about how to run the docker version on ubuntu 18.

Thanks in advance.

**Comment by maburlik** [comment]
We are looking into this on our end. Thanks for identifying the issue.

**Comment by cschertzmsft** [comment]
Ran into this issue this morning.   Just adding my voice to the mix to hope this will get an update soon

**Comment by maburlik** [comment]
See the updated docker hub page. We have created two new tags: 'onebox:u16', 'onebox:u18' and are no longer updating 'latest' tag since it is ambiguous and the one line cluster deployment scenario with the new tags is a great improvement over the old model.

 https://hub.docker.com/_/microsoft-service-fabric-onebox
